#server:
#  port: 3333
#
#spring:
#  data:
#    maria:
#      jbdc-url: jdbc:mariadb://rds-mariadb.cm6lx5azssje.ap-northeast-2.rds.amazonaws.com:3306/admin?useUnicode=yes&characterEncoding=UTF-8
#      driver-class-name: org.mariadb.jdbc.Driver
#      username: admin
#      password: qlalfqjsghahffkdy
#  jpa:
#    properties:
#      hibernate:
#        format_sql: true
#        temp:
#          use_jdbc_metadata_defaults: false
#    generate-ddl: true

server:
  port: 3333

spring:
  data:
    maria:
      jdbc-url: jdbc:mariadb://rds-mariadb.cm6lx5azssje.ap-northeast-2.rds.amazonaws.com:3306/admin?useUnicode=yes&characterEncoding=UTF-8
      driver-class-name: org.mariadb.jdbc.Driver
      username: admin
      password: qlalfqjsghahffkdy
  jpa:
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    generate-ddl: true